"""
Seed 50 historical desk decisions for Desk Brain™.
Real-feeling trading journal entries covering Brent/Urals spreads, ethane arbs,
directional WTI, NGL basis, seasonal spreads, cross-commodity arbs, and carbon trades.
"""
import logging
import json
from datetime import date
from database.db import SessionLocal
from database.models import DeskDecision, User, Book, Counterparty

logger = logging.getLogger(__name__)


DECISIONS_DATA = [
    # ---- Brent/Urals Spread Trades (17) --------------------------------
    {
        "decision_date": date(2023, 2, 14),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF Med 400K bbl / Sell ICE Brent M+1 futures 4x 100K contracts",
        "rationale": "Brent/Urals spread widened to -$7.80/bbl vs 90-day mean of -$5.20. Post-Feb-2022 sanctions had compressed but spread now overshooting fundamentals. Primorsk export volumes unchanged.",
        "market_context": "Brent at $83.20, Urals assessed at $75.40. BDTI subdued. Baltic freight rates stable.",
        "volume": 400000,
        "entry_price": -7.80,
        "exit_price": -5.40,
        "hold_days": 11,
        "pnl_realised": 960000,
        "outcome": "Profitable",
        "lessons_learned": "Spread mean reversion trade works well when freight is stable. Key indicator: BDTI correlation holds at 0.72 over this period.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "sanctions", "mean_reversion"]),
    },
    {
        "decision_date": date(2023, 5, 8),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals FOB Primorsk 500K bbl / Sell Dated Brent forward",
        "rationale": "Spread at -$6.50, historically mean -$4.80. Positive carry given physical demand from India/China refiners replacing European buyers.",
        "market_context": "Brent $75.60, Urals assessed $69.10. Primorsk loadings on schedule. Indian refinery demand strong.",
        "volume": 500000,
        "entry_price": -6.50,
        "exit_price": -4.90,
        "hold_days": 8,
        "pnl_realised": 800000,
        "outcome": "Profitable",
        "lessons_learned": "Indian/Chinese demand substitution creates predictable spread compression. Track VLCC fixtures to Rotterdam vs India as divergence signal.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "india_demand"]),
    },
    {
        "decision_date": date(2023, 9, 12),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF Med 300K bbl / Sell ICE Brent front month",
        "rationale": "Spread widened to -$8.10 on news of EU 7th sanctions package. Historical analysis shows these events overshoot by avg $1.50-2.50/bbl within 2 weeks.",
        "market_context": "Brent $92.40, Urals $84.30. EU sanctions headline risk elevated but physical flows rerouting to Asia.",
        "volume": 300000,
        "entry_price": -8.10,
        "exit_price": -5.80,
        "hold_days": 14,
        "pnl_realised": 690000,
        "outcome": "Profitable",
        "lessons_learned": "Sanctions headlines overshoot physical market reaction. Wait 48-72 hours post-headline before entering — allows dust to settle and avoid catching falling knife.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "sanctions", "event_driven"]),
    },
    {
        "decision_date": date(2024, 2, 6),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF Med 500K bbl / Sell Dated Brent forward — LOSS",
        "rationale": "Spread at -$6.90, targeting reversion to -$4.50 mean. Assumed freight stable based on recent 30-day average.",
        "market_context": "Brent $80.20, Urals $73.30. Baltic Dirty Tanker Index at 1,240. No major VLCC events visible at entry.",
        "volume": 500000,
        "entry_price": -6.90,
        "exit_price": -9.70,
        "hold_days": 6,
        "pnl_realised": -3400000,
        "outcome": "Loss",
        "lessons_learned": "Always model freight separately when trading CIF/CIF spreads. Use BDTI correlation as early warning. A 2.8x freight widening can overwhelm a fundamentally sound spread trade.",
        "failure_mode": "Freight widened 2.8x faster than basis compressed. Baltic Dirty Tanker Index spiked on unexpected VLCC demand from Asia. Should have hedged freight leg separately.",
        "tags": json.dumps(["spread", "urals", "brent", "freight_risk", "loss", "learning"]),
    },
    {
        "decision_date": date(2024, 4, 3),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF Rotterdam 250K bbl / Sell ICE Brent M+1 with freight hedge via FFA",
        "rationale": "Post-February loss, implemented freight-hedged framework. Spread at -$7.20. FFA TD2 used to isolate pure basis trade.",
        "market_context": "Brent $85.40, Urals $78.20. BDTI hedged at 1,280.",
        "volume": 250000,
        "entry_price": -7.20,
        "exit_price": -5.50,
        "hold_days": 9,
        "pnl_realised": 425000,
        "outcome": "Profitable",
        "lessons_learned": "Freight-hedged framework validated. FFA cost $28K, gross pnl $453K. Net improvement vs unhedged approach substantial.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "freight_hedge", "ffa", "framework"]),
    },
    {
        "decision_date": date(2024, 6, 18),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Brent/Dubai EFS — Buy Dubai M+2 swap / Sell ICE Brent M+2",
        "rationale": "EFS at -$3.20 vs 6-month mean -$1.80. Asian refinery turnarounds completing, demand recovery expected.",
        "market_context": "Brent $83.10, Dubai $79.90. EFS at widest since Jan 2024.",
        "volume": 400000,
        "entry_price": -3.20,
        "exit_price": -1.95,
        "hold_days": 12,
        "pnl_realised": 500000,
        "outcome": "Profitable",
        "lessons_learned": "EFS mean reversion reliable when Asian refinery runs recovering. Monitor Singapore complex margin as leading indicator.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "brent", "dubai", "EFS", "asian_demand"]),
    },
    {
        "decision_date": date(2024, 8, 22),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals FOB 350K bbl / Sell Brent futures with freight hedge",
        "rationale": "Spread overshooting at -$9.10 on drone attack news affecting Primorsk briefly. Export volumes confirmed unchanged within 6 hours of news.",
        "market_context": "Brent $78.50, Urals $69.40. Drone attack on Novorossiysk terminal — limited structural impact.",
        "volume": 350000,
        "entry_price": -9.10,
        "exit_price": -6.80,
        "hold_days": 5,
        "pnl_realised": 805000,
        "outcome": "Profitable",
        "lessons_learned": "Geopolitical noise vs fundamental disruption: validate export volumes within 24 hours before sizing. Quick verification prevents missing the trade.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "geopolitical", "event_driven"]),
    },
    {
        "decision_date": date(2024, 11, 5),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF Med 450K bbl / Sell Brent dated — Q4 seasonal",
        "rationale": "Q4 traditionally sees compression as European refiners stock up on cheaper crude. Spread at -$7.50.",
        "market_context": "Brent $74.20, Urals $66.70. European refinery runs strong ahead of winter heating season.",
        "volume": 450000,
        "entry_price": -7.50,
        "exit_price": -5.60,
        "hold_days": 16,
        "pnl_realised": 855000,
        "outcome": "Profitable",
        "lessons_learned": "Q4 Urals/Brent seasonal compression trade consistent over 4 years. European refinery utilisation >90% is the key trigger condition.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "seasonal", "q4"]),
    },
    {
        "decision_date": date(2025, 1, 14),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF 300K bbl / Sell ICE Brent — new year reset trade",
        "rationale": "Spread reset to -$8.40 at year open due to thin liquidity. Fundamentals unchanged. New year flows typically re-anchor spread within 2 weeks.",
        "market_context": "Brent $76.30, Urals $67.90. Market illiquid Jan 2-14.",
        "volume": 300000,
        "entry_price": -8.40,
        "exit_price": -6.20,
        "hold_days": 10,
        "pnl_realised": 660000,
        "outcome": "Profitable",
        "lessons_learned": "January illiquidity creates reliable entry opportunities in spread markets. Size conservatively due to wide bid/offer.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "seasonality", "liquidity"]),
    },
    {
        "decision_date": date(2025, 3, 20),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "M1/M3 Brent time spread — sell prompt, buy deferred on backwardation trade",
        "rationale": "Backwardation widened to $2.40/bbl M1-M3 vs 90-day mean $1.10. OPEC+ cut maintenance driving near-term tightness.",
        "market_context": "Brent M1 $84.20, M3 $81.80. OPEC+ cut compliance 96%.",
        "volume": 600000,
        "entry_price": 2.40,
        "exit_price": 1.15,
        "hold_days": 8,
        "pnl_realised": 750000,
        "outcome": "Profitable",
        "lessons_learned": "Brent time spread mean reversion most reliable when OPEC+ compliance >90%. Monitor monthly OSP adjustments as leading indicator.",
        "failure_mode": None,
        "tags": json.dumps(["time_spread", "brent", "backwardation", "opec"]),
    },
    {
        "decision_date": date(2025, 6, 2),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Brent/WTI EFP — Buy WTI CL futures / Sell ICE Brent futures on wider-than-usual EFP",
        "rationale": "WTI/Brent EFP at -$3.80 vs mean -$2.40. Houston pipeline bottleneck causing WTI weakness. Resolution expected within 3 weeks.",
        "market_context": "Brent $82.10, WTI $78.30. Seaway pipeline maintenance completed, flows resuming.",
        "volume": 500000,
        "entry_price": -3.80,
        "exit_price": -2.30,
        "hold_days": 11,
        "pnl_realised": 750000,
        "outcome": "Profitable",
        "lessons_learned": "Pipeline bottleneck events in Cushing/Houston corridor create reliable EFP widening. Track Cushing inventory builds as resolution signal.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "brent", "wti", "EFP", "pipeline"]),
    },
    {
        "decision_date": date(2025, 8, 15),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF 400K bbl / Sell ICE Brent — freight-hedged post-summer",
        "rationale": "Spread -$7.90, above average. Summer lull in European demand typically reverses September. FFA hedge in place.",
        "market_context": "Brent $78.90, Urals $71.00. BDTI 1,150. European refinery utilisation recovering from summer maintenance.",
        "volume": 400000,
        "entry_price": -7.90,
        "exit_price": -6.10,
        "hold_days": 18,
        "pnl_realised": 720000,
        "outcome": "Profitable",
        "lessons_learned": "Post-summer European refinery restart creates reliable Urals demand uptick. Entry window: late August to mid-September.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "seasonal", "q3_q4_transition"]),
    },
    {
        "decision_date": date(2025, 10, 9),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals FOB 200K bbl / Sell Brent dated — small position, tight stops",
        "rationale": "Spread at -$6.10, slight compression expected on Oct OPEC+ meeting commentary. Small tactical size.",
        "market_context": "Brent $80.40, Urals $74.30. OPEC+ meeting next week, uncertainty high.",
        "volume": 200000,
        "entry_price": -6.10,
        "exit_price": -6.80,
        "hold_days": 4,
        "pnl_realised": -140000,
        "outcome": "Loss",
        "lessons_learned": "Do not enter spread trades within 5 days of OPEC+ meeting — macro shock risk too high vs expected basis move.",
        "failure_mode": "OPEC+ surprised with deeper cut, causing Brent rally while Urals lagged on thin Asian demand. Position too large relative to uncertainty.",
        "tags": json.dumps(["spread", "urals", "brent", "opec_risk", "loss"]),
    },
    {
        "decision_date": date(2025, 12, 3),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF Med 500K bbl / Sell Brent — Q4 seasonal, freight hedged",
        "rationale": "Repeat of Q4 seasonal trade. Spread -$7.80. European refiners stocking ahead of year-end. FFA TD2 hedge at 1,290.",
        "market_context": "Brent $73.80, Urals $66.00. Winter heating demand supporting European runs.",
        "volume": 500000,
        "entry_price": -7.80,
        "exit_price": -5.90,
        "hold_days": 14,
        "pnl_realised": 950000,
        "outcome": "Profitable",
        "lessons_learned": "Q4 Urals/Brent seasonal trade now systematised. Three consecutive years of profitability. Entering as a standing order in Q4 playbook.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "seasonal", "q4", "playbook"]),
    },
    {
        "decision_date": date(2026, 1, 22),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Brent M1/M6 calendar spread — sell front, buy deferred",
        "rationale": "Backwardation steepened to $3.10 M1-M6 on cold snap demand. Mean $1.60. Should revert on demand normalisation.",
        "market_context": "Brent M1 $86.40, M6 $83.30. Cold snap in Northern Europe, temporary demand spike.",
        "volume": 500000,
        "entry_price": 3.10,
        "exit_price": 1.70,
        "hold_days": 7,
        "pnl_realised": 700000,
        "outcome": "Profitable",
        "lessons_learned": "Weather-driven backwardation spikes in Brent revert quickly (5-10 days). Use tight exits — do not overstay as contango risk emerges post-weather event.",
        "failure_mode": None,
        "tags": json.dumps(["time_spread", "brent", "weather", "backwardation"]),
    },
    {
        "decision_date": date(2026, 3, 11),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals 300K bbl / Sell Brent — post-OPEC meeting entry",
        "rationale": "Waited 6 days post OPEC+ March meeting. Spread settled at -$7.40 after initial volatility. Clean entry.",
        "market_context": "Brent $82.00, Urals $74.60. Post-OPEC clarity restored. Freight stable.",
        "volume": 300000,
        "entry_price": -7.40,
        "exit_price": -5.80,
        "hold_days": 10,
        "pnl_realised": 480000,
        "outcome": "Profitable",
        "lessons_learned": "Applying OPEC+ waiting rule from Oct 2025 loss — 5-day post-meeting entry rule working well.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "opec_rule", "process_improvement"]),
    },
    {
        "decision_date": date(2026, 4, 28),
        "commodity": "Urals",
        "strategy_type": "Spread",
        "structure_description": "Buy Urals CIF 400K bbl / Sell Brent forward — freight hedge via FFA TD2",
        "rationale": "Spread -$7.20. Consistent with Q2 mean reversion opportunity. Freight hedged.",
        "market_context": "Brent $83.40, Urals $76.20. BDTI 1,310. Good entry conditions.",
        "volume": 400000,
        "entry_price": -7.20,
        "exit_price": -5.50,
        "hold_days": 9,
        "pnl_realised": 680000,
        "outcome": "Profitable",
        "lessons_learned": "Framework working consistently. Fourth consecutive quarter with positive Urals/Brent spread trade.",
        "failure_mode": None,
        "tags": json.dumps(["spread", "urals", "brent", "freight_hedge", "systematic"]),
    },

    # ---- Ethane Arb Trades (8) ----------------------------------------
    {
        "decision_date": date(2023, 3, 7),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Physical ethane arb: buy US Gulf Coast spot, sell NWE Argus assessed — via Dragon vessel JS Ineos Intrepid",
        "rationale": "NWE-US ethane spread at $80/MT favourable. Freight cost $42/MT via Dragon vessel. Net arb $38/MT. Volume 12,000 MT.",
        "market_context": "US ethane at $195/MT (Mont Belvieu), NWE Argus $275/MT. Dragon vessel available. Rafnes cracker feedstock demand strong.",
        "volume": 12000,
        "entry_price": 195.0,
        "exit_price": 275.0,
        "hold_days": 18,
        "pnl_realised": 456000,
        "outcome": "Profitable",
        "lessons_learned": "Dragon fleet arb economics strongest when NWE premium >$75/MT. Below $65/MT, freight costs squeeze margin too thin.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "dragon_fleet", "physical", "nwe_us_spread"]),
    },
    {
        "decision_date": date(2023, 7, 14),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Financial ethane NWE vs US spread trade — buy Mont Belvieu swaps, sell NWE financial",
        "rationale": "Spread compressed to $65/MT — below physical arb threshold. Financial trade to express view on reversion without physical risk.",
        "market_context": "Mont Belvieu $210/MT, NWE $275/MT. No Dragon vessel slot available. Financial trade only.",
        "volume": 10000,
        "entry_price": 65.0,
        "exit_price": 82.0,
        "hold_days": 12,
        "pnl_realised": 170000,
        "outcome": "Profitable",
        "lessons_learned": "Financial ethane arb effective when no vessel slot. Smaller PnL but zero freight risk. Good complement to physical programme.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "financial", "swap"]),
    },
    {
        "decision_date": date(2024, 1, 9),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Physical US-NWE ethane arb via JS Ineos Insight",
        "rationale": "NWE premium $92/MT vs US. Dragon freight $44/MT net. Arb $48/MT on 11,800 MT. Grangemouth cracker demand confirmed.",
        "market_context": "US ethane $225/MT, NWE $317/MT. JS Ineos Insight available, loading Marcus Hook 15-Jan.",
        "volume": 11800,
        "entry_price": 225.0,
        "exit_price": 317.0,
        "hold_days": 20,
        "pnl_realised": 566400,
        "outcome": "Profitable",
        "lessons_learned": "Grangemouth cracker demand signal (weekly production schedule) is the most reliable leading indicator for NWE ethane demand.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "dragon_fleet", "grangemouth", "physical"]),
    },
    {
        "decision_date": date(2024, 5, 22),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Ethane arb — loaded cargo but NWE prices fell during transit",
        "rationale": "Spread at $78/MT at loading. Dragon vessel JS Ineos Innovation loaded. Spread compressed to $45/MT by arrival.",
        "market_context": "US ethane $240/MT, NWE $318/MT at loading. NWE fell to $285 by delivery due to unexpected European cracker outage reducing demand.",
        "volume": 12100,
        "entry_price": 240.0,
        "exit_price": 285.0,
        "hold_days": 19,
        "pnl_realised": 64500,
        "outcome": "Profitable",
        "lessons_learned": "Thin margin arb. Should have hedged NWE exposure on day of loading via financial swap. Physical arb vulnerable to NWE price moves during 18-20 day transit.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "dragon_fleet", "transit_risk", "hedging_gap"]),
    },
    {
        "decision_date": date(2024, 9, 3),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Rafnes ethane forward purchase vs Grangemouth spot sale — intra-NWE arb",
        "rationale": "Rafnes-Grangemouth price differential at $12/MT. Forward purchase at Rafnes index, spot sale Grangemouth. Low risk, pipeline delivery.",
        "market_context": "Rafnes ethane forward $295/MT, Grangemouth spot $307/MT. Pipeline capacity available.",
        "volume": 8000,
        "entry_price": 295.0,
        "exit_price": 307.0,
        "hold_days": 7,
        "pnl_realised": 96000,
        "outcome": "Profitable",
        "lessons_learned": "Intra-NWE ethane arb between Rafnes and Grangemouth is low-risk, high-consistency. Margins small but reliable. Good use of short-term working capital.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "intra_nwe", "rafnes", "grangemouth"]),
    },
    {
        "decision_date": date(2025, 2, 17),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Physical US-NWE arb via JS Ineos Independence — full vessel load",
        "rationale": "NWE premium $95/MT, strongest in 8 months. Dragon freight $43/MT. Net arb $52/MT. Full vessel load 11,500 MT.",
        "market_context": "US Mont Belvieu $230/MT, NWE Argus $325/MT. Cold winter driving NWE cracker demand. Vessel availability optimal.",
        "volume": 11500,
        "entry_price": 230.0,
        "exit_price": 325.0,
        "hold_days": 21,
        "pnl_realised": 598000,
        "outcome": "Profitable",
        "lessons_learned": "Winter NWE demand spikes create best ethane arb windows. Recommend standing Dragon vessel reservation Oct-Feb for priority loading slots.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "dragon_fleet", "winter_demand", "best_practice"]),
    },
    {
        "decision_date": date(2025, 7, 8),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Financial ethane arb — spread compressed, small financial position",
        "rationale": "Physical arb uneconomic at $62/MT spread. Financial position only. Targeted $75/MT recovery.",
        "market_context": "US ethane $245/MT, NWE $307/MT. Summer NWE demand seasonally low.",
        "volume": 8000,
        "entry_price": 62.0,
        "exit_price": 55.0,
        "hold_days": 9,
        "pnl_realised": -56000,
        "outcome": "Loss",
        "lessons_learned": "Summer NWE ethane demand structurally weak (cracker maintenance season). Do not trade financial ethane spread in June-August unless clear catalyst.",
        "failure_mode": "NWE prices continued falling through summer maintenance period. Spread compressed further rather than recovering.",
        "tags": json.dumps(["arb", "ethane", "financial", "seasonal_error", "loss"]),
    },
    {
        "decision_date": date(2026, 2, 11),
        "commodity": "Ethane",
        "strategy_type": "Arb",
        "structure_description": "Physical US-NWE ethane arb via JS Ineos Intrepid — winter trade",
        "rationale": "NWE premium $88/MT. Dragon freight $44/MT. Net arb $44/MT on 12,400 MT = $545K gross.",
        "market_context": "Mont Belvieu $240/MT, NWE Argus $328/MT. Rafnes cracker running at 95% utilisation.",
        "volume": 12400,
        "entry_price": 240.0,
        "exit_price": 328.0,
        "hold_days": 19,
        "pnl_realised": 545600,
        "outcome": "Profitable",
        "lessons_learned": "Consistent winter ethane arb execution. NWE hedge on day-of-loading locking in $85/MT net after freight. Framework now standard operating procedure.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "ethane", "dragon_fleet", "winter", "standard_process"]),
    },

    # ---- Directional WTI Trades (7) -----------------------------------
    {
        "decision_date": date(2023, 4, 3),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Long WTI NYMEX CL futures 3x 100K contracts on OPEC+ surprise cut",
        "rationale": "OPEC+ announced surprise 1M bbl/day cut. Bought WTI M1 at $80.20. Target $87-90 within 10 days.",
        "market_context": "WTI at $80.20 immediately post OPEC+ announcement. Large positioning shift expected.",
        "volume": 300000,
        "entry_price": 80.20,
        "exit_price": 86.80,
        "hold_days": 8,
        "pnl_realised": 1980000,
        "outcome": "Profitable",
        "lessons_learned": "OPEC+ surprise cuts create strong initial move — buy at announcement, exit within 1-2 weeks as expectation gets priced in. Do not hold through IEA response commentary.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "wti", "opec", "event_driven"]),
    },
    {
        "decision_date": date(2023, 8, 29),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Short WTI NYMEX CL M+1 on demand destruction signal",
        "rationale": "US manufacturing PMI below 47 for 3rd consecutive month. Trucking data weak. Gasoline demand down YoY. Risk/reward favoured short from $88.",
        "market_context": "WTI at $88.00. Fed hawkish. USD strengthening. OPEC compliance strong but demand softening.",
        "volume": 200000,
        "entry_price": 88.00,
        "exit_price": 84.20,
        "hold_days": 11,
        "pnl_realised": 760000,
        "outcome": "Profitable",
        "lessons_learned": "Multiple aligned macro signals (PMI, freight, gasoline demand) required for directional short conviction. Single indicator insufficient.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "wti", "short", "macro", "demand_destruction"]),
    },
    {
        "decision_date": date(2024, 3, 12),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Long WTI ahead of expected OPEC+ meeting — stopped out",
        "rationale": "Anticipated OPEC+ would extend cuts. Entered long at $78.80.",
        "market_context": "WTI $78.80. OPEC+ meeting 2 weeks away. Positioning data net long.",
        "volume": 250000,
        "entry_price": 78.80,
        "exit_price": 76.40,
        "hold_days": 5,
        "pnl_realised": -600000,
        "outcome": "Loss",
        "lessons_learned": "Anticipatory positioning ahead of OPEC+ carries event risk. Stop-loss at 2% should have been tighter at 1.5% given uncertain outcome. OPEC+ messaging was ambiguous.",
        "failure_mode": "OPEC+ deferred decision — market interpreted as weakening commitment, WTI sold off.",
        "tags": json.dumps(["directional", "wti", "opec_risk", "loss", "stop_loss"]),
    },
    {
        "decision_date": date(2024, 7, 5),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Short WTI on global growth concerns — China PMI miss",
        "rationale": "China Caixin PMI at 48.1, miss vs 50.2 expected. WTI at $83. Target $77-78 on demand revision.",
        "market_context": "WTI $83.20. China weakness visible in steel, copper, shipping data.",
        "volume": 300000,
        "entry_price": 83.20,
        "exit_price": 77.80,
        "hold_days": 14,
        "pnl_realised": 1620000,
        "outcome": "Profitable",
        "lessons_learned": "China industrial PMI miss >2 points with confirming industrial commodity signals is a high-conviction directional short trigger.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "wti", "short", "china", "macro"]),
    },
    {
        "decision_date": date(2025, 1, 28),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Long WTI on geopolitical risk premium build — Middle East escalation",
        "rationale": "Strait of Hormuz threat escalated. Risk premium historically $3-6/bbl on this type of event.",
        "market_context": "WTI $72.40. Iran naval incident in Gulf. US carrier group repositioning.",
        "volume": 200000,
        "entry_price": 72.40,
        "exit_price": 70.80,
        "hold_days": 4,
        "pnl_realised": -320000,
        "outcome": "Loss",
        "lessons_learned": "Geopolitical risk premium trades require physical supply disruption, not just threat. This event resolved diplomatically within 36 hours. Wait for confirmed disruption.",
        "failure_mode": "Diplomatic de-escalation within 36 hours — risk premium evaporated. Should have waited for actual supply disruption evidence.",
        "tags": json.dumps(["directional", "wti", "geopolitical", "loss", "risk_premium"]),
    },
    {
        "decision_date": date(2025, 9, 16),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Short WTI on hurricane-related demand destruction — US Gulf Coast impact",
        "rationale": "Hurricane Idalia tracking toward Houston. Refinery demand destruction expected. Short WTI as refineries shut.",
        "market_context": "WTI $76.80. Cat 4 hurricane 48 hours from Galveston landfall.",
        "volume": 150000,
        "entry_price": 76.80,
        "exit_price": 80.20,
        "hold_days": 6,
        "pnl_realised": -510000,
        "outcome": "Loss",
        "lessons_learned": "Hurricanes affect both supply (production) AND demand (refining). Net impact on crude price depends on balance. If supply shut > refinery shut, prices rise. Do not default to short.",
        "failure_mode": "Offshore production shut faster than refineries — net crude supply reduction caused WTI to rally despite refinery demand loss.",
        "tags": json.dumps(["directional", "wti", "hurricane", "loss", "supply_demand_balance"]),
    },
    {
        "decision_date": date(2026, 3, 25),
        "commodity": "WTI",
        "strategy_type": "Directional",
        "structure_description": "Long WTI on confirmed OPEC+ production cut extension",
        "rationale": "OPEC+ unanimously extended 1.66M bbl/day voluntary cuts through Q2 2026. Waited 24 hours post-announcement, entered at $79.80.",
        "market_context": "WTI $79.80. Strong compliance data. Demand recovery in Asia confirmed. Entered post-announcement as per OPEC+ lesson from Apr 2023.",
        "volume": 300000,
        "entry_price": 79.80,
        "exit_price": 84.20,
        "hold_days": 9,
        "pnl_realised": 1320000,
        "outcome": "Profitable",
        "lessons_learned": "24-hour wait post OPEC+ announcement provides better entry price than immediate reaction trade. Applies framework from 2023 lesson.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "wti", "opec", "process_applied"]),
    },

    # ---- NGL Basis Trades (6) -----------------------------------------
    {
        "decision_date": date(2023, 6, 19),
        "commodity": "NGLs",
        "strategy_type": "Basis",
        "structure_description": "Buy NGL CIF NWE physical vs sell Mont Belvieu swap — basis compression trade",
        "rationale": "NWE propane/butane discount to Mont Belvieu wider than normal at -$18/MT. US LPG export capacity constraints resolving, expect parity improvement.",
        "market_context": "Mont Belvieu propane $485/MT, NWE $467/MT. Export terminal maintenance completing.",
        "volume": 30000,
        "entry_price": -18.0,
        "exit_price": -8.0,
        "hold_days": 14,
        "pnl_realised": 300000,
        "outcome": "Profitable",
        "lessons_learned": "US LPG export terminal utilisation data is leading indicator for NWE/US NGL basis. Export constraint resolution = NWE discount compression.",
        "failure_mode": None,
        "tags": json.dumps(["basis", "ngls", "nwe", "mont_belvieu", "export_capacity"]),
    },
    {
        "decision_date": date(2023, 11, 7),
        "commodity": "NGLs",
        "strategy_type": "Basis",
        "structure_description": "NGL winter premium trade — buy Oct forward, sell Nov spot",
        "rationale": "October NGLs pricing at discount to November due to early season heating demand uncertainty. Bought Oct, sold Nov physical.",
        "market_context": "NWE propane Oct $490/MT, Nov $508/MT. Early cold snap expected in November.",
        "volume": 20000,
        "entry_price": -18.0,
        "exit_price": -5.0,
        "hold_days": 21,
        "pnl_realised": 260000,
        "outcome": "Profitable",
        "lessons_learned": "NGL forward curve seasonality trade predictable in Oct-Nov transition. Cold snap forecasts amplify Oct/Nov spread.",
        "failure_mode": None,
        "tags": json.dumps(["basis", "ngls", "seasonal", "winter_premium"]),
    },
    {
        "decision_date": date(2024, 2, 28),
        "commodity": "NGLs",
        "strategy_type": "Basis",
        "structure_description": "Grangemouth vs Rotterdam NGL basis trade — pipeline arb",
        "rationale": "Grangemouth propane at $12/MT premium to Rotterdam due to INEOS plant demand. Sold Grangemouth, bought Rotterdam, covered with pipeline logistics.",
        "market_context": "Grangemouth propane $502/MT, Rotterdam $490/MT. Pipeline capacity available.",
        "volume": 15000,
        "entry_price": 12.0,
        "exit_price": 4.0,
        "hold_days": 8,
        "pnl_realised": 120000,
        "outcome": "Profitable",
        "lessons_learned": "Grangemouth premium appears when INEOS cracker throughput increases. Monitor cracker run schedule weekly.",
        "failure_mode": None,
        "tags": json.dumps(["basis", "ngls", "grangemouth", "rotterdam", "pipeline_arb"]),
    },
    {
        "decision_date": date(2024, 8, 12),
        "commodity": "NGLs",
        "strategy_type": "Basis",
        "structure_description": "NGL quality basis — propane vs butane ratio trade",
        "rationale": "Propane/butane ratio at historical extremes. Bought butane, sold propane financial. Expected ratio normalisation.",
        "market_context": "Propane $475/MT, butane $430/MT. Petrochemical demand for butane seasonally low.",
        "volume": 25000,
        "entry_price": 45.0,
        "exit_price": 52.0,
        "hold_days": 3,
        "pnl_realised": -175000,
        "outcome": "Loss",
        "lessons_learned": "Propane/butane ratio trades require deep petrochemical demand intelligence. Butane seasonal weakness persisted 3 weeks longer than expected.",
        "failure_mode": "Butane petrochemical demand remained depressed as European ethylene cracker utilisation stayed low. Held too long.",
        "tags": json.dumps(["basis", "ngls", "quality_spread", "loss"]),
    },
    {
        "decision_date": date(2025, 4, 14),
        "commodity": "NGLs",
        "strategy_type": "Basis",
        "structure_description": "US-NWE NGL basis compression — export expansion catalyst",
        "rationale": "New Marcus Hook export terminal Phase 2 online — adding 40K MT/month capacity. NWE discount to narrow structurally.",
        "market_context": "NWE propane $470/MT vs Mont Belvieu equivalent $488/MT.",
        "volume": 40000,
        "entry_price": -18.0,
        "exit_price": -9.0,
        "hold_days": 20,
        "pnl_realised": 360000,
        "outcome": "Profitable",
        "lessons_learned": "Terminal capacity expansions are structural basis catalysts. The structural nature of the move (not mean reversion) allows larger size and longer hold.",
        "failure_mode": None,
        "tags": json.dumps(["basis", "ngls", "structural", "export_capacity"]),
    },
    {
        "decision_date": date(2025, 10, 20),
        "commodity": "NGLs",
        "strategy_type": "Basis",
        "structure_description": "NGL winter storage depletion trade — buy spring forward vs sell winter spot",
        "rationale": "Winter NGL storage fill at 5-year low. Winter-spring spread compressed — should widen as storage depletion risk increases.",
        "market_context": "NWE propane Dec $508/MT, Apr $492/MT. Storage 18% below 5-year average.",
        "volume": 20000,
        "entry_price": 16.0,
        "exit_price": 28.0,
        "hold_days": 35,
        "pnl_realised": 240000,
        "outcome": "Profitable",
        "lessons_learned": "Storage deficit trades in NGLs require patience — 4-6 week hold typical. Sized appropriately. Storage reports (Eurogas weekly) are key monitoring tool.",
        "failure_mode": None,
        "tags": json.dumps(["basis", "ngls", "storage", "winter_spring_spread"]),
    },

    # ---- Seasonal Spread Trades (5) ------------------------------------
    {
        "decision_date": date(2023, 10, 2),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Q4 Brent seasonal backwardation trade — sell Dec, buy Mar",
        "rationale": "Historically Dec/Mar Brent backwardation averages $1.80-2.20 in Q4. Entered at $1.40 backwardation expecting widening.",
        "market_context": "Brent Dec $90.20, Mar $88.80. Q4 demand seasonally strong, OPEC+ maintaining cuts.",
        "volume": 500000,
        "entry_price": 1.40,
        "exit_price": 2.10,
        "hold_days": 12,
        "pnl_realised": 350000,
        "outcome": "Profitable",
        "lessons_learned": "Q4 Brent seasonal backwardation trade consistent. Best entry window: first 2 weeks of October.",
        "failure_mode": None,
        "tags": json.dumps(["seasonal", "brent", "q4", "time_spread"]),
    },
    {
        "decision_date": date(2024, 6, 10),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Summer contango trade — Brent M1/M3 contango widening expected",
        "rationale": "Entering Q3, OPEC+ signal supply additions possible. US refinery utilisation high. Contango should widen seasonally.",
        "market_context": "Brent M1 $79.80, M3 $79.20. Slight backwardation. Expected flip to contango.",
        "volume": 400000,
        "entry_price": 0.60,
        "exit_price": -0.80,
        "hold_days": 9,
        "pnl_realised": 560000,
        "outcome": "Profitable",
        "lessons_learned": "Summer contango transition in Brent predictable when OPEC+ supply additions coincide with US refinery high-utilisation period.",
        "failure_mode": None,
        "tags": json.dumps(["seasonal", "brent", "contango", "summer"]),
    },
    {
        "decision_date": date(2024, 12, 3),
        "commodity": "Ethane",
        "strategy_type": "Spread",
        "structure_description": "Winter ethane NWE seasonal premium trade",
        "rationale": "NWE ethane winter premium over summer typically $40-60/MT. Entered physical position at Nov-level pricing.",
        "market_context": "NWE ethane Nov $305/MT, Feb $345/MT. Rafnes cracker winter throughput demand confirmed.",
        "volume": 10000,
        "entry_price": 40.0,
        "exit_price": 58.0,
        "hold_days": 28,
        "pnl_realised": 180000,
        "outcome": "Profitable",
        "lessons_learned": "NWE ethane winter premium trade requires vessel availability to take delivery. Dragon fleet scheduling is the constraint, not the trade logic.",
        "failure_mode": None,
        "tags": json.dumps(["seasonal", "ethane", "winter_premium", "dragon_fleet"]),
    },
    {
        "decision_date": date(2025, 3, 5),
        "commodity": "Brent",
        "strategy_type": "Spread",
        "structure_description": "Spring driving season long Brent — Q2 demand build",
        "rationale": "US gasoline demand typically builds March through May. Bought Brent May futures at $78.40.",
        "market_context": "Brent $78.40. US spring driving season approaching. Refinery utilisation rising from maintenance lows.",
        "volume": 300000,
        "entry_price": 78.40,
        "exit_price": 83.60,
        "hold_days": 22,
        "pnl_realised": 1560000,
        "outcome": "Profitable",
        "lessons_learned": "Spring demand build trade most reliable when: (1) US refinery utilisation recovering, (2) driving season data confirming demand, (3) OPEC+ not signalling supply additions.",
        "failure_mode": None,
        "tags": json.dumps(["seasonal", "brent", "spring", "driving_season"]),
    },
    {
        "decision_date": date(2025, 11, 18),
        "commodity": "NGLs",
        "strategy_type": "Spread",
        "structure_description": "NGL winter heating premium seasonal — butane blend demand",
        "rationale": "Butane blending into LPG for winter heating typically creates Oct-Dec premium of $15-25/MT vs summer. Entered at $8/MT expecting widening.",
        "market_context": "NWE butane $440/MT vs summer average $432/MT. Cold snap forecast 3 weeks out.",
        "volume": 15000,
        "entry_price": 8.0,
        "exit_price": 22.0,
        "hold_days": 18,
        "pnl_realised": 210000,
        "outcome": "Profitable",
        "lessons_learned": "Butane winter blending demand creates 6-8 week seasonal window. Position management key — best exit is when heating season demand peaks, not at meteorological winter start.",
        "failure_mode": None,
        "tags": json.dumps(["seasonal", "ngls", "butane", "winter_blending"]),
    },

    # ---- Cross-Commodity Arbs (4) -------------------------------------
    {
        "decision_date": date(2023, 12, 11),
        "commodity": "Brent",
        "strategy_type": "Arb",
        "structure_description": "Crude-naphtha crack spread — long Brent / short naphtha NWE",
        "rationale": "Naphtha crack at -$8/bbl vs Brent, historically mean -$5. Petrochemical demand for naphtha low seasonally. Expected reversion.",
        "market_context": "Brent $76.20, NWE naphtha CIF at $68.20 (crack -$8/bbl). European olefins demand slow.",
        "volume": 200000,
        "entry_price": -8.0,
        "exit_price": -5.20,
        "hold_days": 13,
        "pnl_realised": 560000,
        "outcome": "Profitable",
        "lessons_learned": "Crude/naphtha crack widening beyond -$7.50 historically reverts within 2-3 weeks. European ethylene cracker run rates are leading indicator.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "cross_commodity", "brent", "naphtha", "crack_spread"]),
    },
    {
        "decision_date": date(2024, 4, 22),
        "commodity": "Carbon",
        "strategy_type": "Arb",
        "structure_description": "EUA/TTF gas correlation arb — buy EUA, sell gas on distorted spread",
        "rationale": "EUA/gas price ratio diverged significantly. When gas falls and EUA holds, cross-commodity relationship creates reversion opportunity.",
        "market_context": "EUA $65/t, TTF gas €28/MWh. Normal ratio disrupted by renewable generation surge.",
        "volume": 25000,
        "entry_price": 65.0,
        "exit_price": 68.40,
        "hold_days": 10,
        "pnl_realised": 85000,
        "outcome": "Profitable",
        "lessons_learned": "EUA/gas correlation arb works within regulatory filing windows. Avoid periods near EUA auction dates — supply-side disruption dominates correlation.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "cross_commodity", "carbon", "eua", "gas"]),
    },
    {
        "decision_date": date(2025, 5, 6),
        "commodity": "Brent",
        "strategy_type": "Arb",
        "structure_description": "Brent/gas oil crack spread normalisation — refinery margin compression",
        "rationale": "Gas oil crack at $28/bbl, 3-year high. European diesel demand recovering. Crack should normalise toward $18-22 seasonal mean.",
        "market_context": "Gas oil crack $28/bbl. European trucking demand recovering post-Q1. Refinery margins historically drive new runs.",
        "volume": 300000,
        "entry_price": 28.0,
        "exit_price": 21.50,
        "hold_days": 16,
        "pnl_realised": 1950000,
        "outcome": "Profitable",
        "lessons_learned": "Extreme crack spreads attract new refinery throughput within 2-4 weeks — self-correcting mechanism. Largest position of 2025, reflected highest conviction.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "cross_commodity", "brent", "gas_oil", "crack_spread"]),
    },
    {
        "decision_date": date(2025, 8, 28),
        "commodity": "NGLs",
        "strategy_type": "Arb",
        "structure_description": "Ethane vs propane substitution arb in NWE crackers",
        "rationale": "NWE crackers can switch between ethane and propane feedstock. Ethane/propane spread reached $45/MT advantage for propane. Crackers switching would compress spread.",
        "market_context": "NWE ethane $295/MT, propane $250/MT. Ethane premium $45/MT — above cracker switch threshold of $30.",
        "volume": 20000,
        "entry_price": 45.0,
        "exit_price": 32.0,
        "hold_days": 12,
        "pnl_realised": 260000,
        "outcome": "Profitable",
        "lessons_learned": "Cracker feedstock substitution economics create reliable spread cap at $30-35/MT. Above threshold, switching demand corrects the spread. Know the cracker economics.",
        "failure_mode": None,
        "tags": json.dumps(["arb", "cross_commodity", "ethane", "propane", "cracker_economics"]),
    },

    # ---- Carbon Trades (3) --------------------------------------------
    {
        "decision_date": date(2023, 11, 28),
        "commodity": "Carbon",
        "strategy_type": "Directional",
        "structure_description": "Long EUA Dec futures ahead of year-end compliance deadline",
        "rationale": "Year-end EUA compliance buying typically creates $3-5 price lift in Nov-Dec. Entered at $68.40, targeting $73-75.",
        "market_context": "EUA Dec $68.40. Power sector short of compliance. Mild weather reducing gas demand and therefore EUA demand near-term — but compliance deadline is hard.",
        "volume": 30000,
        "entry_price": 68.40,
        "exit_price": 72.80,
        "hold_days": 19,
        "pnl_realised": 132000,
        "outcome": "Profitable",
        "lessons_learned": "EUA year-end compliance trade reliable but sizing must reflect EU power generation mix. Warm winters reduce power demand, dampening EUA demand temporarily. Hold through.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "carbon", "eua", "compliance", "seasonal"]),
    },
    {
        "decision_date": date(2024, 6, 4),
        "commodity": "Carbon",
        "strategy_type": "Directional",
        "structure_description": "Short EUA on EU election result — policy uncertainty",
        "rationale": "EU Parliamentary elections produced more conservative result. ETS reform risk elevated. Short EUA at $67.20.",
        "market_context": "EUA $67.20 post-election. Market pricing in potential ETS reform delay or weakening.",
        "volume": 20000,
        "entry_price": 67.20,
        "exit_price": 61.80,
        "hold_days": 10,
        "pnl_realised": 108000,
        "outcome": "Profitable",
        "lessons_learned": "Political event-driven EUA trades have good initial signal but require quick exits — policy effects take months to materialise but price impact is immediate then fades.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "carbon", "eua", "political_risk"]),
    },
    {
        "decision_date": date(2025, 3, 17),
        "commodity": "Carbon",
        "strategy_type": "Directional",
        "structure_description": "Long EUA on cold March driving power generation demand — weather catalyst",
        "rationale": "Coldest March on record in NW Europe driving gas-fired power generation. EUA demand spiking.",
        "market_context": "EUA $58.40. Power sector buying EUAs to cover gas generation. 14-day forecast all below average temperatures.",
        "volume": 25000,
        "entry_price": 58.40,
        "exit_price": 64.20,
        "hold_days": 8,
        "pnl_realised": 145000,
        "outcome": "Profitable",
        "lessons_learned": "Cold weather EUA trades work well in shoulder months (March, October) when gas backup power is highest. Summer/winter months less responsive as renewables or demand lower.",
        "failure_mode": None,
        "tags": json.dumps(["directional", "carbon", "eua", "weather_catalyst"]),
    },
]


def seed_decisions(db=None):
    close_db = False
    if db is None:
        db = SessionLocal()
        close_db = True
    try:
        if db.query(DeskDecision).first():
            logger.info("DeskDecisions already seeded — skipping.")
            return

        trader = db.query(User).filter(User.role == "trader").first()
        books_by_commodity = {}
        for b in db.query(Book).all():
            books_by_commodity[b.commodity.lower()] = b

        def get_book(commodity):
            c = commodity.lower()
            if c in ("brent", "wti", "urals", "crude"):
                return books_by_commodity.get("crude")
            if c == "ethane":
                return books_by_commodity.get("ethane")
            if c in ("ngls", "ngl", "propane", "butane"):
                return books_by_commodity.get("ngls")
            if c in ("carbon", "eua"):
                return books_by_commodity.get("carbon")
            return None

        decisions = []
        for d in DECISIONS_DATA:
            book = get_book(d["commodity"])
            decisions.append(DeskDecision(
                decision_date=d["decision_date"],
                trader_id=trader.id if trader else None,
                book_id=book.id if book else None,
                commodity=d["commodity"],
                strategy_type=d["strategy_type"],
                structure_description=d["structure_description"],
                rationale=d["rationale"],
                market_context=d["market_context"],
                volume=d["volume"],
                entry_price=d["entry_price"],
                exit_price=d["exit_price"],
                hold_days=d["hold_days"],
                pnl_realised=d["pnl_realised"],
                outcome=d["outcome"],
                lessons_learned=d["lessons_learned"],
                failure_mode=d.get("failure_mode"),
                tags=d["tags"] if isinstance(d["tags"], str) else json.dumps(d["tags"]),
            ))

        db.add_all(decisions)
        db.commit()
        logger.info(f"Seeded {len(decisions)} desk decisions.")
        return len(decisions)
    except Exception as e:
        db.rollback()
        logger.error(f"seed_decisions error: {e}")
        raise
    finally:
        if close_db:
            db.close()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    seed_decisions()
